version = 1

test_patterns = [
  "**/*.spec.ts",
  "**/*.e2e-spec.ts"
]

exclude_patterns = [
  "**/node_modules/**",
  "migrations/**",
  "**/__mocks__/**"
]

[[analyzers]]
name = "javascript"
enabled = true
